title: "ph3mt blog"
description: "Appunti, analisi e note tecniche"
url: "https://ph3mt.github.io"
baseurl: "/ph3mt.github.io-blog"

remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache   # <— AGGIUNTO
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

locale: it
timezone: Europe/Rome

nav:
  main: []

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      related: true
      share: true
      show_date: true
