title: "ph3mt blog"
description: "Appunti, analisi e note tecniche"
url: "https://ph3mt.github.io"            # dominio del profilo
baseurl: "/ph3mt.github.io-blog"          # nome del repo (sito di progetto)

# Tema via remote_theme (compatibile Pages)
remote_theme: mmistakes/minimal-mistakes@4.24.0

# Skin (tema colori): default, dark, air, neon...
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Impostazioni lingua/ora
locale: it
timezone: Europe/Rome

# Navigazione (la definiamo in _data/navigation.yml)
nav:
  main: []

# Default per i post
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      related: true
      share: true
      show_date: true

# Percorsi asset (non obbligatorio, solo promemoria)
# assets/images/... le usi con {{ '/assets/...' | relative_url }}
